"""pk changes for jdmatch

Revision ID: 4162be973fde
Revises: 4469ae1616af
Create Date: 2026-02-18 01:04:44.842930

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4162be973fde"
down_revision: str | Sequence[str] | None = "4469ae1616af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop the sequence default first
    op.execute("ALTER TABLE jdmatchdtl ALTER COLUMN id DROP DEFAULT")

    op.alter_column(
        "jdmatchdtl",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.Uuid(),
        existing_nullable=False,
        postgresql_using="md5(id::text)::uuid",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jdmatchdtl",
        "id",
        existing_type=sa.Uuid(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
