"""Initial migration

Revision ID: 4469ae1616af
Revises:
Create Date: 2026-02-18 00:40:36.446461

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4469ae1616af"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("jdmatchdtl", "jd", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("jdmatchdtl", "score", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "jdmatchdtl", "explanation", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "jdmatchdtl", "file_name", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_index(op.f("ix_jdmatchdtl_file_id"), table_name="jdmatchdtl")
    op.create_index(
        op.f("ix_jdmatchdtl_file_id"), "jdmatchdtl", ["file_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jdmatchdtl_file_id"), table_name="jdmatchdtl")
    op.create_index(
        op.f("ix_jdmatchdtl_file_id"), "jdmatchdtl", ["file_id"], unique=False
    )
    op.alter_column(
        "jdmatchdtl", "file_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "jdmatchdtl", "explanation", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("jdmatchdtl", "score", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("jdmatchdtl", "jd", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
