"""description of changes

Revision ID: 7a05941e401b
Revises: e57209174471
Create Date: 2026-02-21 11:05:19.851387

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7a05941e401b"
down_revision: Union[str, Sequence[str], None] = "e57209174471"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jdmatchdtl",
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jdmatchdtl", "status")
    # ### end Alembic commands ###
