"""new resume_url field

Revision ID: e57209174471
Revises: 4162be973fde
Create Date: 2026-02-20 22:41:57.194586

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e57209174471"
down_revision: str | Sequence[str] | None = "4162be973fde"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jdmatchdtl",
        sa.Column("resume_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jdmatchdtl", "resume_url")
    # ### end Alembic commands ###
